### ISSUE TITLE
Not visible in the list of plugins

### ISSUE THREAD

**Issue by epigraphe** [i-Vertix/glpi-modifications#1]
Good day. Trying to install the plugin as usual:
Downloaded and put in the plugins folder.
Nothing appeared in the list of plugins.
What else needs to be done?

**Comment by flex-pgum** [comment]
Hi, sorry for the late reply.
What GLPI version do you use?

Regarding the installation:
I recommend to uninstall the old mod plugin, remove all plugin related files and install this plugin (please make sure to pick the right plugin version that corresponds to the GLPI version).
Also make sure that all files have the required access rights (apache user has to delete/move/copy images and files for backup
purposes).

**Comment by joschi99** [comment]
If you are using the source file you need to rename the directory to "mod", otherwise is not visible.
