### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fbrochini** [i-Vertix/glpi-modifications#2]
Hello, after all the instalation, I run the plugin in GLPI, but it won´t aply the modifications neither the default  settings like the background and the logos of the plugin.

(I've dowloaded the original modifications source and rewrite the oldies files within this ones, before that GLPI couldn´t reach the plugins page gettin 'connection' errors)

**Comment by flex-pgum** [comment]
Hi, sorry for the late reply.
What GLPI version do you use?

Regarding the installation:
I recommend to uninstall the old mod plugin, remove all plugin related files and install this plugin (please make sure to pick the right plugin version that corresponds to the GLPI version).
Also make sure that *all* files have the required access rights (apache user has to delete/move/copy images and files for backup 
purposes).
