### ISSUE TITLE
Plugin doesn't alter logos and wallpaper

### ISSUE THREAD

**Issue by usbezerra** [i-Vertix/glpi-modifications#3]
After installed in a clean GLPI, from apache user, this plugin can't apply modifications in wallpaper or logos. Only modification accepted on GLPI is Header, 

This plugin can't create backup from original files

**Comment by flex-pgum** [comment]
Hi, which GLPI version do you use?

Most likely this is a permission problem. Also, depending on permissions, the apache user might not be able to create the directory "backups" which is created in the /plugins/mod folder.

Here is a list of files which are moved/replaced by the plugin (path starting from glpi root directory):

- /templates/layout/page_card_notlogged.html.twig
- /templates/layout/parts/head.html.twig
- /pics/logos/logo-G-100-black.png
- /pics/logos/logo-G-100-grey.png
- /pics/logos/logo-G-100-white.png
- /pics/logos/logo-GLPI-100-black.png
- /pics/logos/logo-GLPI-100-grey.png
- /pics/logos/logo-GLPI-100-white.png
- /pics/logos/logo-GLPI-250-black.png
- /pics/logos/logo-GLPI-250-grey.png
- /pics/logos/logo-GLPI-250-white.png
- /pics/favicon.ico

Just as a note, if the files got replaced properly you might want to delete the browser cache. This is one of the most common issues.
