### ISSUE TITLE
All time errer Backup folder not created

### ISSUE THREAD

**Issue by taib27** [i-Vertix/glpi-modifications#4]
Backup folder not created  ?!!
tout fonctionne bien , j'ai deja installé un plugin manuellement et il fonctionne bien sans problème . 
j'utilise GLpi10 avec apache . 

d'où cela peut venir ?  

i already install other plugin manually and its work properly

**Comment by flex-pgum** [comment]
Hi, it seems like this is a problem with permissions. Please make sure the apache user is able to write and read in the mod directory.
What you can also try is to manually create the following folders and apply write/read permissions for apache user/group:
"<glpi_root>/plugins/mod/backups"
"<glpi_root>/plugins/mod/backups/twig"
"<glpi_root>/plugins/mod/backups/logos"

**Comment by taib27** [comment]
thnx it works perfectly !!
the two folders twig end logo wasn't there  ^_^

**Comment by flex-pgum** [comment]
Thank you for your reply.
I will look into it asap, maybe there is a case where they are not created properly

**Comment by flex-pgum** [comment]
Hi @ftoledo , thanks for the hint! I will look into this and release a new version which migrates all files to the /files/_plugins/mod directory to ensure easier plugin setup and a more stable use.
To be honest, I did not know about this folder so I simply used the /plugins/mod/ folder for backups/configurations (which works if permissions are granted correctly, I use it myself)

**Comment by ftoledo** [comment]
If plugins need to write and save files (beyond using the database) the "<glpi_root>/files/_plugins" path is a standard place to go for this task. Because the "files" directory is a requirement for the webserver to have permission to write to it from the glpi installation.
On the other hand, it might be good that in the plugin configuration screen, under the file upload form, you can see a list with permission checks for the /pics and /templates files. For example:

```
List of GLPI files where write access is needed:

FAIL   /templates/layout/page_card_notlogged.html.twig 
FAIL   /templates/layout/parts/head.html.twig
OK     /pics/logos/logo-G-100-black.png
OK     /pics/logos/logo-G-100-grey.png
OK     /pics/logos/logo-G-100-white.png
OK     /pics/logos/logo-GLPI-100-black.png
OK     /pics/logos/logo-GLPI-100-grey.png
OK     /pics/logos/logo-GLPI-100-white.png
OK     /pics/logos/logo-GLPI-250-black.png
OK     /pics/logos/logo-GLPI-250-grey.png
OK     /pics/logos/logo-GLPI-250-white.png
OK     /pics/favicon.ico
```

thanks!!
